### PR TITLE
Simplify XapianMSetIterator implementation

### PR DESCRIPTION
**Pull request by ojwb**
Eliminate mBegin and mEnd by using <xapian/iterator.h> and
MSet::begin(), and eliminate an unnecessary pointer indirection
from mCurrent.

Right now, this patch is mostly there for comments, or even just to park it somewhere it won't get lost - it doesn't actually fix bugs as such, rather it simplifies the implementation, reduces the memory overhead (number of memory allocations and total usage) and should be a bit faster.  

But while doing this tweak, I noticed that the semantics of `prev()` seem a bit odd (stemming from the asymmetry of `begin()` and `end()` in C++ - `begin()` points to the first element, but `end()` points to just after the last element).

To iterate forwards, the example code in the docs is:

```
   // retrieve the first 10 results
   XapianMSet *mset = xapian_enquire_get_mset (enquire, 0, 10, NULL);

   unsigned int size = xapian_mset_get_size (mset);

   XapianMSetIterator *iter = xapian_mset_get_begin (mset);

   while (xapian_mset_iterator_next (iter))
     {
       g_print ("Result %u of %u: %.3f [docid=%u]",
                xapian_mset_iterator_get_rank (iter) + 1,
                size,
                xapian_mset_iterator_get_weight (iter),
                xapian_mset_iterator_get_doc_id (iter, NULL));

       XapianDocument *doc = xapian_mset_iterator_get_document (iter, NULL);

       // ... use the document
     }
```

But the equivalent going backwards would be:

```
   // retrieve the first 10 results
   XapianMSet *mset = xapian_enquire_get_mset (enquire, 0, 10, NULL);

   unsigned int size = xapian_mset_get_size (mset);

   XapianMSetIterator *iter = xapian_mset_get_end (mset);

   gboolean more = xapian_mset_iterator_prev (iter);
   while (more)
     {
       more = xapian_mset_iterator_prev (iter);

       g_print ("Result %u of %u: %.3f [docid=%u]",
                xapian_mset_iterator_get_rank (iter) + 1,
                size,
                xapian_mset_iterator_get_weight (iter),
                xapian_mset_iterator_get_doc_id (iter, NULL));

       XapianDocument *doc = xapian_mset_iterator_get_document (iter, NULL);

       // ... use the document
     }
```

The key difference is the loop changes from:

```
 while (xapian_mset_iterator_next (iter))
    {
      // ...
    }
```

to

```
   gboolean more = xapian_mset_iterator_prev (iter);
   while (more)
     {
       more = xapian_mset_iterator_prev (iter);

       // ...
     }
```

Essentially the first time we call `prev()` we get back the end iterator which we must not dereference, but the return value tell us "is the iterated `XapianMSet` non-empty?"

If the first call was OK, subsequent calls always move us to a valid element, and return whether we can safely move back again.

This feels ungainly to work with (it took me several goes to get the second loop right) - is it really intended to work like that?

### CODE REVIEW

**Comment by ebassi** [comment]
The original idea for the MSetIterator was to use a stack-allocated structure, with the possibility of an heap-allocated version for use in other languages. Sadly, the initial implementation had issues when it came to the JavaScript/C memory management, which meant that I had to port it to GObject instances.

Initially, I started with something similar to the [GSequence](https://developer.gnome.org/glib/stable/glib-Sequences.html) iterator API — `is_begin()`/`is_end()` to be used as the conditions for the loop, and `next()`/`prev()` pairs:

```cpp
while (!xapian_mset_iter_is_end (iter)) {
  iter = xapian_mset_iter_next (iter);
  ...
}

while (!xapian_mset_iter_is_begin (iter)) {
  iter = xapian_mset_iter_prev (iter);
  ...
}
```

Then I ended up matching what C++ does, because of the switch to GObject and modifying the instance in place.

I think is a bit too late to change the semantics of the iterators, now. Maybe it would be possible to migrate to the GSequence model while keeping the existing semantics in place — but it's definitely something to consider for the next development cycle, at this point.

**Comment by ebassi** [comment]
In the meantime, I'll merge this PR.

**Comment by ojwb** [comment]
One option is just to deprecate the ability to iterate backwards, and instead provide a way to get the iterator at a given position - e.g. `xapian_mset_get_iter_at_pos(gint position)` (akin to `g_sequence_get_iter_at_pos()`).  Generally you want to iterate search results starting at the top of the list, and in the rarer cases where you want to do something different, random access is much more versatile than just being able to go backwards.

The C++ API provides random access via `MSet::operator[]` (which is O(1)).  The real reason C++ provides `MSetIterator::operator--` at all is that providing it is a requirement for being a random-access iterator (because a random-access iterator has to also satisfy the requirements of being a bidirectional iterator).

**Comment by cosimoc** [comment]
@ebassi Ping?

**Comment by ebassi** [comment]
@ojwb Deprecating `prev()` is perfectly acceptable to me.

**Comment by ebassi** [comment]
We can land this, and then create a new PR for the deprecation of `xapian_mset_iter_prev()` and addition of `xapian_mset_get_iter_at_pos()`.

**Comment by ptomato** [comment]
This seems to break on CI:
```
xapian-mset-iterator.cc: In member function 'bool IteratorData::prev()':
xapian-mset-iterator.cc:132:20: error: no match for 'operator+=' (operand types are 'Xapian::MSetIterator' and 'Xapian::doccount {aka unsigned int}')
           mCurrent += xapian_mset_get_internal (mMSet)->size ();
                    ^
```
Are we somehow using a different Xapian version there than the one in the Flatpak runtime?

**Comment by ojwb** [comment]
Ah, `MSet::operator+=` was missing prior to 1.3.7.  Sorry, I only tested with 1.4.x.

I think the simplest way to address this is just to loop and call `operator++` `size()` times for Xapian < 1.4.  That might appear to be unnecessarily O(n), but actually `operator++` really just inlines to `++index` and the compiler should be able to unroll a known-length loop and collapse it into essentially `index += size()`.  I'll take a quick look at the generated code to confirm that happens, and open a follow-on PR.

**Pull request merged**
